version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk17
    commands:
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests  # Skip tests to check if the build works

  build:
    commands:
      - echo "Building the project..."
      - mvn package -DskipTests  # Skip tests again

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - target/*.jar
