version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Use 'corretto17' instead of 'openjdk17' for Amazon Corretto
    commands:
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests  # Skip tests to check if the build works
      - java -version  # Verify Java version

  build:
    commands:
      - echo "Building the project..."
      - mvn package -DskipTests  # Skip tests again

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - target/*.jar
